services:
  crypto-info-mcp:
      build: 
        context: .
        args:
          VERSION: ${VERSION:-local}
        tags:
          - "crypto-info-mcp:${VERSION:-local}"
      image: crypto-info-mcp:${VERSION:-local}
      container_name: crypto-info-mcp
      restart: unless-stopped
      ports:
        - "18123:8123"
      networks:
        - bridge_server
      environment:
        COINGECKO_API_KEY: ${COINGECKO_API_KEY:-}
        TELEGRAM_API_ID: ${TELEGRAM_API_ID:-}
        TELEGRAM_API_HASH: ${TELEGRAM_API_HASH:-}
        TELEGRAM_SESSION_STRING: ${TELEGRAM_SESSION_STRING:-}

networks:
  bridge_server:
    external: true
